### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by damaya**
Add support for ldap

### CODE REVIEW

**Comment by damaya** [comment]
Tested with vagrant and working with internal project

**Comment by mauricios** [comment]
LDAP extension as any other extension should be added in the settings of the playbook that uses this role, and this should not be a default, here: https://github.com/Aplyca/ansible-role-lamp/blob/master/defaults/main.yml#L7 you can see an example on how to add the mysql extension.

**Comment by damaya** [comment]
Thanks for the feedback. In this case, i finally figured out that also in the custom settings new modules can be added, in example at settings/web.yml:
php_modules:
    30: curl
    31: xsl
    32: intl
    33: imagick
    34: gd
    35: ldap

**Comment by damaya** [comment]
Closing this PR.

**Pull request closed without merging**
